config/routes.rb
Rails.application.routes.draw do
  get 'registered/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
resources:users
   root 'pages#index'
  get '/pages/check'
  get '/pages/artists'
  get 'pages/privacy'
  get '/pages/about_us'
  get '/pages/all_cities'
  get '/pages/event_providers'
  get '/pages/jobs'
  get '/pages/index'
  get '/pages/terms'
  get '/users/new'
  get '/users/index'
  get '/registered/index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def index
end
def jobs
end
def event_providers
end
def artists
end
def all_cities
end
def about_us
end
def privacy
end
def terms
end
end

app/controllers/registered_controller.rb
class RegisteredController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
  @users=User.all
end
def new
  @user=User.new
end
def create
  @user = User.create(user_params)
  if @user.save
            redirect_to registered_index_path,  :notice => "Your post was saved"
  end
end

private

def user_params
  params.require(:user).permit(:Name, :Email, :City, :Age)
end
    def view

    end

    def update

    end

    def destroy

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registered_helper.rb
module RegisteredHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Showr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/artists.html.erb
<!DOCTYPE html>
<html class="html" lang="en-US">
 <head>

  <script type="text/javascript">
   if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["jquery-1.8.3.min.js", "museutils.js", "jquery.watch.js", "artists.css"], "outOfDate":[]};
</script>
  
  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2015.0.0.309"/>
  <title>Partners • Artists</title>
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="css/site_global.css?4052507572"/>
  <link rel="stylesheet" type="text/css" href="css/master_b-master.css?67586553"/>
  <link rel="stylesheet" type="text/css" href="css/artists.css?4097630015" id="pagesheet"/>
  <!--[if lt IE 9]>
  <link rel="stylesheet" type="text/css" href="css/iefonts_artists.css?3886719811"/>
  <![endif]-->
  <!-- Other scripts -->
  <script type="text/javascript">
   document.documentElement.className += ' js';
var __adobewebfontsappname__ = "muse";
</script>
  <!-- JS includes -->
  <script type="text/javascript">
   document.write('\x3Cscript src="' + (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//webfonts.creativecloud.com/asap:n7,n4:default;viga:n4:default;quicksand:n7:default.js" type="text/javascript">\x3C/script>');
</script>
   </head>
 <body>

  <div class="clearfix" id="page"><!-- column -->
   <div class="position_content" id="page_position_content">
    <div class="browser_width colelem" id="u518-bw">
     <div id="u518"><!-- group -->
      <div class="clearfix" id="u518_align_to_page">
       <a class="nonblock nontext clearfix grpelem" id="u540-4" href="index.html"><!-- content --><p id="u540-2">SHOWR</p></a>
       <a class="nonblock nontext clearfix grpelem" id="u584-4" href="index.html#thelist"><!-- content --><h3 id="u584-2">SIGN UP</h3></a>
      </div>
     </div>
    </div>
    <div class="clearfix colelem" id="u596-4"><!-- content -->
     <p>Perform in front of a bigger crowd.</p>
    </div>
    <div class="clearfix colelem" id="u605-4"><!-- content -->
     <p>Let's face it, you like performing in front of people that are having fun, that are screaming at the top of their lungs. You like being appreciated. Well, Showr appreciate artists. Ask your promoter to have a talk with us.</p>
    </div>
    <div class="verticalspacer"></div>
    <div class="browser_width colelem" id="u541-bw">
     <div id="u541"><!-- column -->
      <div class="clearfix" id="u541_align_to_page">
       <div class="clearfix colelem" id="pu519-4"><!-- group -->
        <div class="clearfix grpelem" id="u519-4"><!-- content -->
         <p>SHOWR</p>
        </div>
        <div class="clearfix grpelem" id="u520-4"><!-- content -->
         <p>CORPORATE</p>
        </div>
        <div class="clearfix grpelem" id="u521-4"><!-- content -->
         <p>SOCIAL</p>
        </div>
       </div>
       <div class="clearfix colelem" id="pu522-4"><!-- group -->
        <a class="nonblock nontext clearfix grpelem" id="u522-4" <%= link_to "About us",pages_about_us_path %><!-- content --></a>
        <a class="nonblock nontext clearfix grpelem" id="u535-4" <%= link_to "Event Providers",pages_event_providers_path %></a>
        <div class="clearfix grpelem" id="u528-4"><!-- content -->
         <p>Tumblr</p>
        </div>
       </div>
       <div class="clearfix colelem" id="pu523-4"><!-- group -->
        <a class="nonblock nontext clearfix grpelem" id="u523-4" <%= link_to "Jobs",pages_jobs_path %></a>
        <a class="nonblock nontext MuseLinkActive clearfix grpelem" id="u532-4" <%= link_to "Artists",pages_artists_path %></a>
        <div class="clearfix grpelem" id="u529-4"><!-- content -->
         <p>Twitter</p>
        </div>
       </div>
       <div class="clearfix colelem" id="pu524-4"><!-- group -->
        <a class="nonblock nontext clearfix grpelem" id="u524-4" <%= link_to "Terms",pages_terms_path %></a>
        <a class="nonblock nontext clearfix grpelem" id="u612-4" href="mailto:help@showr.com"><!-- content --><p>Support</p></a>
        <div class="clearfix grpelem" id="u530-4"><!-- content -->
         <p>Facebook</p>
        </div>
       </div>
       <div class="clearfix colelem" id="pu525-4"><!-- group -->
        <a class="nonblock nontext clearfix grpelem" id="u525-4" <%= link_to "Privacy",pages_privacy_path %></a>
        <div class="clearfix grpelem" id="u531-4"><!-- content -->
         <p>Instagram</p>
        </div>
       </div>
       <div class="clearfix colelem" id="u533-6"><!-- content -->
        <p id="u533-4"><span id="u533">Made with </span><span id="u533-2">♥</span><span id="u533-3"> in India</span></p>
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>
  <!-- JS includes -->
  <script type="text/javascript">
   if (document.location.protocol != 'https:') document.write('\x3Cscript src="http://musecdn.businesscatalyst.com/scripts/4.0/jquery-1.8.3.min.js" type="text/javascript">\x3C/script>');
</script>
  <script type="text/javascript">
   window.jQuery || document.write('\x3Cscript src="scripts/jquery-1.8.3.min.js" type="text/javascript">\x3C/script>');
</script>
  <script src="scripts/museutils.js?183364071" type="text/javascript"></script>
  <script src="scripts/jquery.watch.js?71412426" type="text/javascript"></script>
  <!-- Other scripts -->
  <script type="text/javascript">
   $(document).ready(function() { try {
(function(){var a={},b=function(a){if(a.match(/^rgb/))return a=a.replace(/\s+/g,"").match(/([\d\,]+)/gi)[0].split(","),(parseInt(a[0])<<16)+(parseInt(a[1])<<8)+parseInt(a[2]);if(a.match(/^\#/))return parseInt(a.substr(1),16);return 0};(function(){$('link[type="text/css"]').each(function(){var b=($(this).attr("href")||"").match(/\/?css\/([\w\-]+\.css)\?(\d+)/);b&&b[1]&&b[2]&&(a[b[1]]=b[2])})})();(function(){$("body").append('<div class="version" style="display:none; width:1px; height:1px;"></div>');
for(var c=$(".version"),d=0;d<Muse.assets.required.length;){var f=Muse.assets.required[d],g=f.match(/([\w\-\.]+)\.(\w+)$/),k=g&&g[1]?g[1]:null,g=g&&g[2]?g[2]:null;switch(g.toLowerCase()){case "css":k=k.replace(/\W/gi,"_").replace(/^([^a-z])/gi,"_$1");c.addClass(k);var g=b(c.css("color")),h=b(c.css("background-color"));g!=0||h!=0?(Muse.assets.required.splice(d,1),"undefined"!=typeof a[f]&&(g!=a[f]>>>24||h!=(a[f]&16777215))&&Muse.assets.outOfDate.push(f)):d++;c.removeClass(k);break;case "js":k.match(/^jquery-[\d\.]+/gi)&&
typeof $!="undefined"?Muse.assets.required.splice(d,1):d++;break;default:throw Error("Unsupported file type: "+g);}}c.remove();if(Muse.assets.outOfDate.length||Muse.assets.required.length)c="Some files on the server may be missing or incorrect. Clear browser cache and try again. If the problem persists please contact website author.",(d=location&&location.search&&location.search.match&&location.search.match(/muse_debug/gi))&&Muse.assets.outOfDate.length&&(c+="\nOut of date: "+Muse.assets.outOfDate.join(",")),d&&Muse.assets.required.length&&(c+="\nMissing: "+Muse.assets.required.join(",")),alert(c)})()})();
/* body */
Muse.Utils.transformMarkupToFixBrowserProblemsPreInit();/* body */
Muse.Utils.detectScreenResolution();/* HiDPI screens */
Muse.Utils.prepHyperlinks(true);/* body */
Muse.Utils.resizeHeight()/* resize height */
Muse.Utils.fullPage('#page');/* 100% height page */
Muse.Utils.showWidgetsWhenReady();/* body */
Muse.Utils.transformMarkupToFixBrowserProblems();/* body */
} catch(e) { if (e && 'function' == typeof e.notify) e.notify(); else Muse.Assert.fail('Error calling selector function:' + e); }});
</script>
   </body>
</html>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html class="html" lang="en-US">
 <head>

  <script type="text/javascript">
   if(typeof Muse == "undefined") window.Muse = {}; window.Muse.assets = {"required":["jquery-1.8.3.min.js", "museutils.js", "jquery.musepolyfill.bgsize.js", "jquery.watch.js", "webpro.js", "index.css"], "outOfDate":[]};
</script>
  
  <meta http-equiv="Content-type" content="text/html;charset=UTF-8"/>
  <meta name="generator" content="2015.0.0.309"/>
  <title>Showr - Go Out Every Night.</title>
  <!-- CSS -->
  <link rel="stylesheet" type="text/css" href="css/site_global.css?4052507572"/>
  <link rel="stylesheet" type="text/css" href="css/master_a-master.css?4179487295"/>
  <link rel="stylesheet" type="text/css" href="css/index.css?4144138961" id="pagesheet"/>
  <!--[if lt IE 9]>
  <link rel="stylesheet" type="text/css" href="css/iefonts_index.css?389043978"/>
  <![endif]-->
  <!-- Other scripts -->
  <script type="text/javascript">
   document.documentElement.className += ' js';
var __adobewebfontsappname__ = "muse";
</script>
  <!-- JS includes -->
  <script type="text/javascript">
   document.write('\x3Cscript src="' + (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//webfonts.creativecloud.com/holtwood-one-sc:n4:default;open-sans:n3,n4:default;muli:n4,i4:default;quicksand:n7:default;asap:n7,n4:default;viga:n4:default;montserrat:n4:default;abel:n4:default.js" type="text/javascript">\x3C/script>');
</script>
   </head>
 <body>

  <div class="clearfix" id="page"><!-- column -->
   <div class="position_content" id="page_position_content">
    <div class="clearfix colelem" id="pu127"><!-- group -->
     <div class="browser_width grpelem" id="u127-bw">
      <div class="museBGSize" id="u127"><!-- column -->
       <div class="clearfix" id="u127_align_to_page">
        <div class="position_content" id="u127_position_content">
         <div class="clearfix colelem" id="pu119-4"><!-- group -->
          <a class="nonblock nontext MuseLinkActive clearfix grpelem" id="u119-4" href="/pages/index.html"><!-- content --><p id="u119-2">SHOWR</p></a>
          <a class="nonblock nontext anim_swing rounded-corners clearfix grpelem" id="u114-4" href="/pages/index.html#thelist"><!-- content --><h3 id="u114-2">SHOW INTEREST</h3></a>
         </div>
         <div class="clearfix colelem" id="u116-4"><!-- content -->
          <h1>Go out for a different show every night.</h1>
         </div>
         <div class="clearfix colelem" id="u118-4"><!-- content -->
          <p>Experience more events with the SHOWR Pass, starting at ₹ 1200 per month.</p>
         </div>
         <a class="nonblock nontext anim_swing rounded-corners clearfix colelem" id="u126-4" href="/pages/index.html#thelist"><!-- content --><p id="u126-2">GET ON THE LIST</p></a>
         <div class="clearfix colelem" id="pu134-4"><!-- group -->
          <div class="clearfix grpelem" id="u134-4"><!-- content -->
           <p id="u134-2">SHOWR is currently scheduled to launch across 7 cities.</p>
          </div>
          <a class="nonblock nontext rounded-corners clearfix grpelem" id="u142-4" href="/pages/all_cities.html"><!-- content --><p id="u142-2">SEE THEM ALL</p></a>
         </div>
        </div>
       </div>
      </div>
     </div>
     <div class="clearfix grpelem" id="u139-4"><!-- content -->
      <p>⍟</p>
     </div>
    </div>
    <div class="browser_width colelem" id="u224-bw">
     <div id="u224"><!-- group -->
      <div class="clearfix" id="u224_align_to_page">
       <div class="clearfix grpelem" id="u200-13"><!-- content -->
        <p id="u200">&nbsp;</p>
        <p id="u200-8"><span id="u200-2">B</span><span id="u200-3">rowse</span><span id="u200-4">t</span><span id="u200-5">he</span><span id="u200-6">s</span><span id="u200-7">hows</span></p>
        <p id="u200-9">&nbsp;</p>
        <p id="u200-11">Access hundreds of shows every month from small gigs and parties, to concerts and festivals. Showr has something for everybody.</p>
       </div>
       <div class="clearfix grpelem" id="u237-13"><!-- content -->
        <p id="u237">&nbsp;</p>
        <p id="u237-8"><span id="u237-2">P</span><span id="u237-3">ick</span><span id="u237-4">y</span><span id="u237-5">our</span><span id="u237-6">s</span><span id="u237-7">how</span></p>
        <p id="u237-9">&nbsp;</p>
        <p id="u237-11">New shows drop at 12 pm up to 2 days in advance. Choose an event you’d like to see, claim your spot on the guest list, and you’re in!</p>
       </div>
       <div class="clearfix grpelem" id="u238-14"><!-- content -->
        <p id="u238">&nbsp;</p>
        <p id="u238-9"><span id="u238-2">#</span><span id="u238-3">M</span><span id="u238-4">AKE</span><span id="u238-5">S</span><span id="u238-6">OME</span><span id="u238-7">S</span><span id="u238-8">HOWR</span></p>
        <p id="u238-10">&nbsp;</p>
        <p id="u238-12">Arrive at the venue and tell them you’re on the Showr Guestlist. No fees, no hassle. Check in and make some noise.</p>
       </div>
      </div>
     </div>
    </div>
    <a class="anchor_item colelem" id="thelist"></a>
    <div class="clearfix colelem" id="ppu257-4"><!-- group -->
     <div class="clearfix grpelem" id="pu257-4"><!-- column -->
      <div class="clearfix colelem" id="u257-4"><!-- content -->
       <p id="u257-2">Just fill this short form &amp; you're in.</p>
      </div>
      <p></p>
      <form class="form-grp clearfix colelem" id="widgetu264" ><!-- none box --></form>
<%= form_for User.new do |f| %>
<div class="fld-grp clearfix grpelem" id="widgetu277" data-required="true"><!-- none box -->
        
<p>
	<%= f.text_field :Name, :placeholder => "Name" %>

</p>
</div>
<div class="fld-grp clearfix grpelem" id="widgetu265" data-required="true" data-type="email">
<p>
	<%= f.text_field :Email, :placeholder => "Email" %>

</p></div>
<div class="fld-grp clearfix grpelem" id="widgetu283" data-required="true"><!-- none box -->
<p>
	<%= f.text_field :City, :placeholder => "City" %>

</p></div>
<div class="fld-grp clearfix grpelem" id="widgetu410" data-required="true">
<p>
	<%= f.text_field :Age, :placeholder => "Age" %>

</p></div>
<input class="submit-btn NoWrap grpelem" id="u274-17" type="submit" value="" tabindex="5">


<% end %>

<hr><hr>

     </div>
     <div class="clearfix grpelem" id="u242-8"><!-- content -->
      <h2 id="u242-2">Get yourself on the first</h2>
      <h2 id="u242-4">Showr list.</h2>
      <h2 id="u242-5">&nbsp;</h2>
      <p id="u242-6">&nbsp;</p>
     </div>
     <div class="clearfix grpelem" id="u598-4"><!-- content -->
      <p>Get on the first Showr list and experience Showr before everyone else. No sign up required and it's completely free. Why do it?</p>
     </div>
    </div>
    <div class="clearfix colelem" id="ppu252-4"><!-- group -->
     <div class="clearfix grpelem" id="pu252-4"><!-- column -->
      <div class="clearfix colelem" id="u252-4"><!-- content -->
       <p id="u252-2">Get notified the moment we launch.</p>
      </div>
      <div class="clearfix colelem" id="u253-4"><!-- content -->
       <p id="u253-2">More shows for cities with maximum people.</p>
      </div>
      <div class="clearfix colelem" id="u254-4"><!-- content -->
       <p id="u254-2">Share us with your loved ones and we'll surprise you.</p>
      </div>
     </div>
     <div class="clearfix grpelem" id="u249-6"><!-- content -->
      <p id="u249-3"><span id="u249">&nbsp;</span><span id="u249-2">✉</span></p>
      <p>&nbsp;</p>
     </div>
     <div class="clearfix grpelem" id="u250-4"><!-- content -->
      <p>&nbsp;✈</p>
     </div>
     <div class="clearfix grpelem" id="u251-4"><!-- content -->
      <p>♥</p>
     </div>
     <div class="clearfix grpelem" id="u415-9"><!-- content -->
      <p>By filling this form, you are agreeing to our <a class="nonblock" <%= link_to "Privacy Policy" ,pages_privacy_path %></a></p>
      <p>This isn't a sign up process.</p>
     </div>
    </div>
    <div class="browser_width colelem" id="u407-bw">
     <div id="u407"><!-- group -->
      <div class="clearfix" id="u407_align_to_page">
       <div class="clearfix grpelem" id="pu417-7"><!-- column -->
        <div class="clearfix colelem" id="u417-7"><!-- content -->
         <p id="u417">&nbsp;</p>
         <p id="u417-3">What is Showr?</p>
         <p id="u417-4">&nbsp;</p>
         <p id="u417-5">&nbsp;</p>
        </div>
        <div class="clearfix colelem" id="u419-10"><!-- content -->
         <p>Showr lets you go to as many events&nbsp; you like for as low as ₹ 1200 per month.</p>
         <p>&nbsp;</p>
         <p>Showr, pronounced as &quot;Shor&quot;, means Noise in Hindi. We want you to be the noise of the party. <span id="u419-5">#</span>MakeSomeShowr</p>
         <p>&nbsp;</p>
        </div>
       </div>
       <div class="clearfix grpelem" id="pu418-6"><!-- column -->
        <div class="clearfix colelem" id="u418-6"><!-- content -->
         <p id="u418">&nbsp;</p>
         <p id="u418-3">How many shows a month?</p>
         <p id="u418-4">&nbsp;</p>
        </div>
        <div class="clearfix colelem" id="u421-7"><!-- content -->
         <p>There is no limit as such on how many shows you can go to!</p>
         <p>&nbsp;</p>
         <p>But, you can only put your name on one guest list at a time. Once you attend a show, you can put your name down for the next one.</p>
        </div>
        <a class="nonblock nontext anim_swing rounded-corners clearfix colelem" id="u424-4" href="/pages/index.html#thelist"><!-- content --><p id="u424-2">TWEET&nbsp; SOME&nbsp; Qs</p></a>
       </div>
       <div class="clearfix grpelem" id="pu420-5"><!-- column -->
        <div class="clearfix colelem" id="u420-5"><!-- content -->
         <p id="u420">&nbsp;</p>
         <p id="u420-3">When do we go live?</p>
        </div>
        <div class="clearfix colelem" id="u422-7"><!-- content -->
         <p>We'll be rolling out pretty soon across 7 cities in India. However, this is just the start.</p>
         <p>&nbsp;</p>
         <p>Till then, share us with your peers. The more people we get on the list, the more shows&nbsp; we&nbsp; bring to your city.</p>
        </div>
       </div>
      </div>
     </div>
    </div>
    <div class="verticalspacer"></div>
    <div class="browser_width colelem" id="u425-bw">
     <div id="u425"><!-- column -->
      <div class="clearfix" id="u425_align_to_page">
       <div class="clearfix colelem" id="pu426-4"><!-- group -->
        <div class="clearfix grpelem" id="u426-4"><!-- content -->
         <p>SHOWR</p>
        </div>
        <div class="clearfix grpelem" id="u427-4"><!-- content -->
         <p>REACH OUT</p>
        </div>
        <div class="clearfix grpelem" id="u428-4"><!-- content -->
         <p>SOCIAL</p>
        </div>
       </div>
       <div class="clearfix colelem" id="pu429-4"><!-- group -->
        <a class="nonblock nontext clearfix grpelem" id="u429-4" <%= link_to "About us",pages_about_us_path %><!-- content --></a>
        <a class="nonblock nontext clearfix grpelem" id="u434-4" <%= link_to "Event Providers",pages_event_providers_path %></a>
        <div class="clearfix grpelem" id="u436-4"><!-- content -->
         <p>Tumblr</p>
        </div>
       </div>
       <div class="clearfix colelem" id="pu431-4"><!-- group -->
        <a class="nonblock nontext clearfix grpelem" id="u431-4" <%= link_to "Jobs",pages_jobs_path %></a>
        <a class="nonblock nontext clearfix grpelem" id="u440-4" <%= link_to "Artists",pages_artists_path %></a>
        <div class="clearfix grpelem" id="u437-4"><!-- content -->
         <p>Twitter</p>
        </div>
       </div>
       <div class="clearfix colelem" id="pu432-4"><!-- group -->
        <a class="nonblock nontext clearfix grpelem" id="u432-4" <%= link_to "Terms",pages_terms_path %></a>
        <a class="nonblock nontext clearfix grpelem" id="u611-4" href="mailto:help@showr.com"><!-- content --><p>Support</p></a>
        <div class="clearfix grpelem" id="u438-4"><!-- content -->
         <p>Facebook</p>
        </div>
       </div>
       <div class="clearfix colelem" id="pu433-4"><!-- group -->
        <a class="nonblock nontext clearfix grpelem" id="u433-4" <%= link_to "Privacy",pages_privacy_path %></a>
        <div class="clearfix grpelem" id="u439-4"><!-- content -->
         <p>Instagram</p>
        </div>
       </div>
       <div class="clearfix colelem" id="u441-6"><!-- content -->
        <p id="u441-4"><span id="u441">Made with </span><span id="u441-2">♥</span><span id="u441-3"> in India</span></p>
       </div>
      </div>
     </div>
    </div>
   </div>
  </div>
  <div class="preload_images">
   <img class="preload" src="images/u274-17-r.png" alt=""/>
   <img class="preload" src="images/u274-17-m.png" alt=""/>
   <img class="preload" src="images/u274-17-fs.png" alt=""/>
   <img class="preload" src="images/u274-17-r_2x.png" alt=""/>
   <img class="preload" src="images/u274-17-m_2x.png" alt=""/>
   <img class="preload" src="images/u274-17-fs_2x.png" alt=""/>
  </div>

   </body>
</html>